//ホーム
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { TodoList } from "./components/todoList";
import { Header } from "./components/header";
import { InputTodo } from "./components/inputTodo";
import { Divider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });//これなに

const Home = () => {
  return (
    <>
      <Head>
        <title>Next Todo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Divider margin={5}/>
        <InputTodo />
        <Divider margin={5} />
        <TodoList />
      </main>
    </>
  );
}

export default Home;